insert into zespoly values(null,'﻿Schiller',null);
insert into zespoly values(null,'Aurora',null);
insert into zespoly values(null,'Ennio Moricone',null);
insert into zespoly values(null,'Alex Vargas',null);
insert into zespoly values(null,'Don Broco',null);
insert into zespoly values(null,'Yungblud',null);
insert into zespoly values(null,'Alex Vargas',null);
insert into zespoly values(null,'Cory Henry ',null);
insert into zespoly values(null,'Tom Odell',null);
insert into zespoly values(null,'You Me At Six',null);
insert into zespoly values(null,'Andrea Bocelli',null);
insert into zespoly values(null,'Flogging Molly',null);
insert into zespoly values(null,'Years&Years',null);
insert into zespoly values(null,'Architects',null);
insert into zespoly values(null,'Shortparis',null);
insert into zespoly values(null,'Einar Selvik i Ivar Bjørnson',null);
insert into zespoly values(null,'Bernhoft',null);
insert into zespoly values(null,'Amine',null);
insert into zespoly values(null,'Ofenbach',null);
insert into zespoly values(null,'Brass Against',null);
insert into zespoly values(null,'IAMX',null);
insert into zespoly values(null,'Steven Wilson',null);
insert into zespoly values(null,'The Neighbourhood',null);
insert into zespoly values(null,'While She Sleeps',null);
insert into zespoly values(null,'Good Charlotte',null);
insert into zespoly values(null,'Slash',null);
insert into zespoly values(null,'Shining',null);
insert into zespoly values(null,'Tommy Cash',null);
insert into zespoly values(null,'Twenty One Pilots',null);
insert into zespoly values(null,'David Duchovny',null);
insert into zespoly values(null,'Health',null);
insert into zespoly values(null,'Algiers',null);
insert into zespoly values(null,'Uriah Heep',null);
insert into zespoly values(null,'Bastille',null);
insert into zespoly values(null,'Vök',null);
insert into zespoly values(null,'Lany',null);
insert into zespoly values(null,'Uriah Heep',null);
insert into zespoly values(null,'Tender',null);
insert into zespoly values(null,'Rival Sons',null);
insert into zespoly values(null,'ZAZ',null);
insert into zespoly values(null,'Haken',null);
insert into zespoly values(null,'Alestorm',null);
insert into zespoly values(null,'Dodie',null);
insert into zespoly values(null,'Nicki Minaj',null);
insert into zespoly values(null,'Dire Straits Experience',null);
insert into zespoly values(null,'GoGo Penguin',null);
insert into zespoly values(null,'GrandMaster Flash',null);
insert into zespoly values(null,'Laibach',null);
insert into zespoly values(null,'Shakin' Stevens',null);
insert into zespoly values(null,'Dance with the Dead',null);
insert into zespoly values(null,'Australian Pink Floyd Show',null);
insert into zespoly values(null,'Morcheeba',null);
insert into zespoly values(null,'Balthazar',null);
insert into zespoly values(null,'Deaf Havana',null);
insert into zespoly values(null,'Peter Hammill',null);
insert into zespoly values(null,'DakhaBrakha',null);
insert into zespoly values(null,'White Lies',null);
insert into zespoly values(null,'DakhaBrakha',null);
insert into zespoly values(null,'Megan Davies',null);
insert into zespoly values(null,'Jess Glynne',null);
insert into zespoly values(null,'Lil Xan',null);
insert into zespoly values(null,'Paris',null);
insert into zespoly values(null,'Don Airey',null);
insert into zespoly values(null,'Kamasi Washington',null);
insert into zespoly values(null,'HRVY',null);
insert into zespoly values(null,'Florence + The Machine',null);
insert into zespoly values(null,'Kimbra',null);
insert into zespoly values(null,'Postmodern Jukebox',null);
insert into zespoly values(null,'Korpiklaani',null);
insert into zespoly values(null,'John Mayall',null);
insert into zespoly values(null,'Blood Youth',null);
insert into zespoly values(null,'The Blaze',null);
insert into zespoly values(null,'Cancer Bats',null);
insert into zespoly values(null,'The Soft Moon',null);
insert into zespoly values(null,'Madrugada',null);
insert into zespoly values(null,'Trombone Shorty',null);
insert into zespoly values(null,'UDO',null);
insert into zespoly values(null,'Dave Matthews Band',null);
insert into zespoly values(null,'Sofi Tukker',null);
insert into zespoly values(null,'Godsmack',null);
insert into zespoly values(null,'Larkin Poe',null);
insert into zespoly values(null,'GZA',null);
insert into zespoly values(null,'Enigma',null);
insert into zespoly values(null,'Shawn Mendes',null);
insert into zespoly values(null,'Devin Townsend',null);
insert into zespoly values(null,'Sleep',null);
insert into zespoly values(null,'The Neal Morse Band',null);
insert into zespoly values(null,'Marillion Weekend',null);
insert into zespoly values(null,'Alan Walker',null);
insert into zespoly values(null,'Passenger',null);
insert into zespoly values(null,'Little Big',null);
insert into zespoly values(null,'Emmure',null);
insert into zespoly values(null,'HVOB',null);
insert into zespoly values(null,'Poets of the Fall',null);
insert into zespoly values(null,'Goran Bregović',null);
insert into zespoly values(null,'All Them Witches',null);
insert into zespoly values(null,'dEUS',null);
insert into zespoly values(null,'Elton John',null);
insert into zespoly values(null,'Bobby McFerrin',null);
insert into zespoly values(null,'Stave Hackett',null);
insert into zespoly values(null,'Enrique Iglesias',null);
insert into zespoly values(null,'Lenny Kravitz',null);
insert into zespoly values(null,'Jack Savoretti',null);
insert into zespoly values(null,'Andrea Bocelli',null);
insert into zespoly values(null,'Glen Hansard',null);
insert into zespoly values(null,'Monster Truck',null);
insert into zespoly values(null,'Sólstafir',null);
insert into zespoly values(null,'Die Arzte',null);
insert into zespoly values(null,'Built to Spill',null);
insert into zespoly values(null,'Alvaro Soler',null);
insert into zespoly values(null,'Joe Bonamassa',null);
insert into zespoly values(null,'Michelle Gurevich',null);
insert into zespoly values(null,'Jamiroquai',null);
insert into zespoly values(null,'Men I Trust',null);
insert into zespoly values(null,'Chris Botti',null);
insert into zespoly values(null,'Die Antwoord',null);
insert into zespoly values(null,'Bryan Ferry',null);
insert into zespoly values(null,'Slayer',null);
insert into zespoly values(null,'Maroon 5',null);
insert into zespoly values(null,'Tool',null);
insert into zespoly values(null,'Alice in Chains,',null);
insert into zespoly values(null,'Black Rebel Motocycle Club',null);
insert into zespoly values(null,'Godsmack',null);
insert into zespoly values(null,'KISS',null);
insert into zespoly values(null,'Disturbed',null);
insert into zespoly values(null,'Rod Stewart',null);
insert into zespoly values(null,'Kraftwerk',null);
insert into zespoly values(null,'Rhye',null);
insert into zespoly values(null,'Apparat',null);
insert into zespoly values(null,'Bjarki Live AV',null);
insert into zespoly values(null,'Fatima Al Qadiri live',null);
insert into zespoly values(null,'GAIKA',null);
insert into zespoly values(null,'GusGus',null);
insert into zespoly values(null,'Jazzanova live',null);
insert into zespoly values(null,'Lisa Morgenstern',null);
insert into zespoly values(null,'Matthew Dear',null);
insert into zespoly values(null,'The Mouse Outfit',null);
insert into zespoly values(null,'Dead Can Dance',null);
insert into zespoly values(null,'Muse',null);
insert into zespoly values(null,'Backstreet Boys',null);
insert into zespoly values(null,'Halestorm',null);
insert into zespoly values(null,'Toto',null);
insert into zespoly values(null,'Slipknot',null);
insert into zespoly values(null,'Testament, ',null);
insert into zespoly values(null,'Amon Amarth',null);
insert into zespoly values(null,'Powerwolf',null);
insert into zespoly values(null,'In Flame ',null);
insert into zespoly values(null,'Soulfly ',null);
insert into zespoly values(null,'Possessed',null);
insert into zespoly values(null,'Sabaton ',null);
insert into zespoly values(null,'Within Temptation',null);
insert into zespoly values(null,'King Diamond',null);
insert into zespoly values(null,'Emperor',null);
insert into zespoly values(null,'Hatebreed',null);
insert into zespoly values(null,'Phil Collins',null);
insert into zespoly values(null,'Diana Krall',null);
insert into zespoly values(null,'Travis Scott ',null);
insert into zespoly values(null,'Vampire Weekend',null);
insert into zespoly values(null,'The 1975 ',null);
insert into zespoly values(null,'Greta van Fleet',null);
insert into zespoly values(null,'Lil Uzi Vert',null);
insert into zespoly values(null,'Sheck Wes ',null);
insert into zespoly values(null,'Rudimental ',null);
insert into zespoly values(null,'Anna Calvi ',null);
insert into zespoly values(null,'Kodaline',null);
insert into zespoly values(null,'Mark Knopfler',null);
insert into zespoly values(null,'Bon Jovi',null);
insert into zespoly values(null,'Opeth',null);
insert into zespoly values(null,'Fish',null);
insert into zespoly values(null,'Tesseract',null);
insert into zespoly values(null,'Sermon',null);
insert into zespoly values(null,'Dream Theater',null);
insert into zespoly values(null,'Richie Kotzen',null);
insert into zespoly values(null,'Foreigner',null);
insert into zespoly values(null,'Il Divo',null);
insert into zespoly values(null,'P!nk',null);
insert into zespoly values(null,'Rammstein',null);
insert into zespoly values(null,'Thirty Seconds to Mars',null);
insert into zespoly values(null,'Status Quo',null);
insert into zespoly values(null,'Ziggy Marley',null);
insert into zespoly values(null,'Daughters',null);
insert into zespoly values(null,'The Gaslamp Killer',null);
insert into zespoly values(null,'Perfect Son',null);
insert into zespoly values(null,'Lebanon Hanover',null);
insert into zespoly values(null,'Boogarins',null);
insert into zespoly values(null,'The Comet Is Coming',null);
insert into zespoly values(null,'Bamba Pana & Makaveli',null);
insert into zespoly values(null,'Metallica',null);
insert into zespoly values(null,'Ghost',null);
insert into zespoly values(null,'Bokassa',null);
insert into zespoly values(null,'Michael Buble',null);
insert into zespoly values(null,'David Garrett',null);
insert into zespoly values(null,'Eros Ramazotti',null);
insert into zespoly values(null,'Sarah Brightman',null);
insert into zespoly values(null,'a-ha',null);
insert into zespoly values(null,'Wardruna',null);
insert into zespoly values(null,'Annihilator',null);
insert into zespoly values(null,'Chris de Burgh',null);
insert into zespoly values(null,'Royal Republic',null);
insert into zespoly values(null,'Bullet For My Valentine',null);
